// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/mebr0/snake-game/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// BaseSnake is an autogenerated mock type for the BaseSnake type
type BaseSnake struct {
	mock.Mock
}

// Body provides a mock function with given fields:
func (_m *BaseSnake) Body() []domain.Point {
	ret := _m.Called()

	var r0 []domain.Point
	if rf, ok := ret.Get(0).(func() []domain.Point); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Point)
		}
	}

	return r0
}

// Grow provides a mock function with given fields: p
func (_m *BaseSnake) Grow(p domain.Point) {
	_m.Called(p)
}

// Head provides a mock function with given fields:
func (_m *BaseSnake) Head() domain.Point {
	ret := _m.Called()

	var r0 domain.Point
	if rf, ok := ret.Get(0).(func() domain.Point); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.Point)
	}

	return r0
}

// Move provides a mock function with given fields: dx, dy
func (_m *BaseSnake) Move(dx int, dy int) bool {
	ret := _m.Called(dx, dy)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(dx, dy)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
